### ISSUE TITLE
Bug Modal

### ISSUE THREAD

**Issue by Coemgen4** [SwagOverflow/kidoikoiaki#7]
Lors du premier clique sur le bouton "Afficher statistiques", la contenu de la modal est affiché en petit, au deuxieme clique SANS LA FERMER, le contenu s'affiche correctement.

**Comment by Grimbode** [comment]
Bug was caused because highcharts canvas was drawn while the modal was hidden. The fix was to simply wait for the modal to be fully shown before calling the highcharts function
